before_install:
   - chmod +x gradlew
   - mkdir "$ANDROID_HOME/licenses" || true
   - ./gradlew dependencies || true

language: android
jdk:
   - oraclejdk8

env:
  global:
      - ANDROID_API_LEVEL=29
      - ANDROID_BUILD_TOOLS_VERSION=29.0.0

script:
   - ./gradlew clean build -i --continue connectedCheck -PdisablePreDex --stacktrace

dist: trusty

android:
   components:
   # Uncomment the lines below if you want to
   # use the latest revision of Android SDK Tools
   - sys-img-x86-android-29
   - sys-img-armeabi-v7a-android-17
   - tools
   - platform-tools
   - build-tools-$ANDROID_BUILD_TOOLS_VERSION
