language: android
before_install:
  - chmod +x gradlew
android:
 components:
   - tools 
   - platform-tools
   - build-tools-27.1.1
   - android-27

script:
 - ./gradlew build connectedCheck
 licenses:
  - '.+'
